- hosts: localhost
  gather_facts: no
  vars:
    test: testvalue
    local_variable: localvalue
  tasks:
  - debug:
      var: input_variable
  
  - set_fact: should_do_thing=no
    when: input_variable is defined and input_variable != ''

  - set_fact: should_do_thing=yes
    when: input_variable is not defined or input_variable == ''

  - name: "Facts - input"
    set_fact:
      new1: >-
        {{ '{{ test }}' if should_do_thing|bool else 'nope' }}
    delegate_to: localhost

  - name: "Debug - input"
    debug:
      var: new1
    delegate_to: localhost

  - name: "Facts - extra"
    set_fact:
      new2: >-
        {{ '{{ test }}' if extra_variable else 'nope' }}
    delegate_to: localhost
  - name: "Debug - extra"
    debug:
      var: new2
    delegate_to: localhost

  - name: "Facts - local"
    set_fact:
      new3: >-
        {{ '{{ test }}' if local_variable else 'nope' }}
    delegate_to: localhost
  - name: "Debug - local"
    debug:
      var: new3
    delegate_to: localhost

